name: api_mock
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3 
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: 1.1.0
  http: ^0.13.3
  intl: 0.18.1
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  intl_utils: ^2.8.7
  json_serializable: ^6.7.0
flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/core/l10n/arb
  output_dir: lib/core/l10n/generated
  use_deferred_loading: false